import { effect, isSignal } from '../core/reactive.ts';
import { createScope, onCleanup, withOwner } from '../core/owner.ts';
import { Fragment, Text, Comment, h, isVNode } from './vnode.ts';
import { isEventProp, setDirectEvent, setDelegatedEvent, installDelegatedEvents } from './events.ts';

const SVG_NS = 'http://www.w3.org/2000/svg';
const BOOLEAN_ATTRS = new Set(['disabled', 'checked', 'selected', 'multiple', 'required', 'autofocus', 'hidden', 'open', 'readonly']);
const PROPERTY_KEYS = new Set(['value', 'checked', 'selected', 'muted', 'currentTime', 'volume', 'indeterminate']);
const ATTRIBUTE_NAMES = { className: 'class', htmlFor: 'for', acceptCharset: 'accept-charset', httpEquiv: 'http-equiv', autoComplete: 'autocomplete', autoFocus: 'autofocus', autoPlay: 'autoplay', colSpan: 'colspan', rowSpan: 'rowspan', maxLength: 'maxlength', minLength: 'minlength', readOnly: 'readonly', tabIndex: 'tabindex' };
const URL_ATTRIBUTES = new Set(['href', 'src', 'action', 'formaction', 'cite', 'poster', 'xlink:href']);
let trustedTypesPolicy = null;
function resolveValue(v) { let value = v, seen = new Set(); while (isSignal(value) || typeof value === 'function') { if (seen.has(value)) break; seen.add(value); value = isSignal(value) ? value.value : value(); } return value; }
function dynamicEffect(v, apply) { if (isSignal(v)) return effect(() => apply(v.value), { sync: true }); if (typeof v === 'function') return effect(() => apply(v()), { sync: true }); apply(v); return null; }
function setStyle(el, value, previous = {}) { if (typeof value === 'string') { el.style.cssText = value; return value; } value ||= {}; for (const k of Object.keys(previous || {})) if (!(k in value)) k.startsWith('--') ? el.style.removeProperty(k) : el.style[k] = ''; for (const [k, v] of Object.entries(value)) { if (v == null) k.startsWith('--') ? el.style.removeProperty(k) : el.style[k] = ''; else if (k.startsWith('--')) el.style.setProperty(k, String(v)); else el.style[k] = typeof v === 'number' && !/^(opacity|zIndex|flex|fontWeight|lineHeight)$/.test(k) ? `${v}px` : String(v); } return value; }
function setClass(el, value) { const classValue = typeof value === 'string' ? value : Array.isArray(value) ? value.filter(Boolean).join(' ') : value && typeof value === 'object' ? Object.entries(value).filter(([, v]) => v).map(([k]) => k).join(' ') : ''; if (classValue) el.setAttribute('class', classValue); else el.removeAttribute('class'); }
function safeURL(value, key) { const text = String(value).trim(); if (!URL_ATTRIBUTES.has(key.toLowerCase()) || !text) return text; try { const protocol = new URL(text, typeof location !== 'undefined' ? location.href : 'http://localhost/').protocol; if (protocol === 'http:' || protocol === 'https:' || protocol === 'mailto:' || protocol === 'tel:' || protocol === 'blob:' || (key.toLowerCase() === 'src' && protocol === 'data:')) return text; return ''; } catch { return ''; } }
function report(el, key, value) { try { globalThis.__LITHE_DEVTOOLS__?.record?.({ type: 'dom', element: el, key, value, traceId: globalThis.__LITHE_CORRELATION_ID__ || null, cause: globalThis.__LITHE_REACTIVE_CAUSE__ || null, at: Date.now() }); } catch { } }
export function __setAttribute(el, key, value, previous, options = {}) { if (key === 'key' || key === 'ref' || key === 'children') return; if (key === 'class' || key === 'className') { setClass(el, value); return report(el, key, value); } if (key === 'style') { setStyle(el, value, previous); return report(el, key, value); } if (key === 'html') { if (value?.__trustedHTML) el.innerHTML = value.value; else throw new Error('Raw HTML requires trustedHTML(value).'); return; } if (key.startsWith('bind:')) return; if (isEventProp(key)) { if (value?.__litheEventSymbol) { let fn; const lazy = async function (event) { if (!fn) { const mod = await import(value.module); fn = mod[value.exportName]; if (typeof fn !== 'function') throw new TypeError(`Event symbol ${value.exportName} is not callable`); } return fn.call(this, event, value.captures ?? null); }; options.delegateEvents !== false ? setDelegatedEvent(el, key, lazy) : setDirectEvent(el, key, lazy, previous); } else options.delegateEvents !== false ? setDelegatedEvent(el, key, value) : setDirectEvent(el, key, value, previous); return; } const attribute = ATTRIBUTE_NAMES[key] || key; if (BOOLEAN_ATTRS.has(key.toLowerCase())) { value ? el.setAttribute(attribute, '') : el.removeAttribute(attribute); if (key in el) el[key] = Boolean(value); return report(el, key, value); } if (PROPERTY_KEYS.has(key) && key in el) { const next = value ?? ''; if (el[key] !== next) el[key] = next; return report(el, key, value); } const safe = safeURL(value, attribute); value == null || value === false || (URL_ATTRIBUTES.has(attribute.toLowerCase()) && !safe) ? el.removeAttribute(attribute) : el.setAttribute(attribute, URL_ATTRIBUTES.has(attribute.toLowerCase()) ? safe : String(value)); report(el, key, value); }
function setupBinding(el, key, target) { const prop = key.slice(5); if (!target?.__litheSignal || Object.getOwnPropertyDescriptor(target, 'value')?.set === undefined) throw new Error(`bind:${prop} requires a writable signal.`); const dispose = effect(() => { const next = target.value; if (el[prop] !== next) el[prop] = next ?? ''; }, { sync: true }); const event = prop === 'value' ? 'input' : 'change', listener = () => target.value = el[prop]; el.addEventListener(event, listener); onCleanup(() => { dispose(); el.removeEventListener(event, listener); }); }
export function __mountChild(parent, child, before, options) { if (isSignal(child) || typeof child === 'function') { const start = document.createComment('lithe:start'), end = document.createComment('lithe:end'); parent.insertBefore(start, before); parent.insertBefore(end, before); let nodes = [], scope = null; const dispose = effect(cleanup => { const value = resolveValue(child); scope?.dispose(); for (const n of nodes) n.remove(); const frag = document.createDocumentFragment(); scope = createScope(() => __mountAny(frag, value, null, options)); nodes = scope.value.nodes; parent.insertBefore(frag, end); cleanup(() => { scope?.dispose(); scope = null; for (const n of nodes) n.remove(); nodes = []; }); }, { sync: true }); onCleanup(() => { dispose(); scope?.dispose(); start.remove(); end.remove(); for (const n of nodes) n.remove(); }); return { nodes: [start, ...nodes, end] }; } return __mountAny(parent, child, before, options); }
function mountNativeElement(parent, type, props = {}, children = [], before, options = {}) { const svg = options.svg || type === 'svg', el = svg ? document.createElementNS(SVG_NS, type) : document.createElement(type); parent.insertBefore(el, before); const childOptions = { ...options, svg }; for (const [key, source] of Object.entries(props || {})) { if (key === 'ref' || key === 'children') continue; if (key.startsWith('bind:')) { setupBinding(el, key, source); continue; } if (isEventProp(key)) { __setAttribute(el, key, source, undefined, childOptions); continue; } let previous; const dispose = dynamicEffect(source, next => { __setAttribute(el, key, next, previous, childOptions); previous = next; }); if (dispose) onCleanup(dispose); } for (const child of children) __mountChild(el, child, null, childOptions); if (typeof props?.ref === 'function') { props.ref(el); onCleanup(() => props.ref(null)); } return { nodes: [el] }; }
export function __mountAny(parent, value, before, options = {}) { if (value == null || value === false || value === true) return { nodes: [] }; if (value?.__litheCompiledElement) return mountNativeElement(parent, value.type, value.props, value.children, before, options); if (value?.__litheCompiledTemplate) { const t = document.createElement('template'); t.innerHTML = value.html; const frag = t.content.cloneNode(true), nodes = [...frag.childNodes], markers = new Map(), walker = document.createTreeWalker(frag, 128); let n; while ((n = walker.nextNode())) { const m = String(n.data || '').match(/^l:(\d+)$/); if (m) markers.set(Number(m[1]), n); } for (let i = 0; i < value.bindings.length; i++) { const marker = markers.get(i); if (!marker) continue; __mountChild(marker.parentNode, value.bindings[i], marker, options); marker.remove(); } parent.insertBefore(frag, before); return { nodes }; } if (value?.__litheStaticTemplate) { const t = document.createElement('template'); t.innerHTML = value.html; const frag = t.content.cloneNode(true), nodes = [...frag.childNodes]; parent.insertBefore(frag, before); return { nodes }; } if (Array.isArray(value)) { const nodes = []; for (const item of value) nodes.push(...__mountChild(parent, item, before, options).nodes); return { nodes }; } if (typeof value === 'string' || typeof value === 'number' || typeof value === 'bigint') { const node = document.createTextNode(String(value)); parent.insertBefore(node, before); return { nodes: [node] }; } if (!isVNode(value)) { const node = document.createTextNode(String(value)); parent.insertBefore(node, before); return { nodes: [node] }; } const vnode = value; if (vnode.type === Text) return __mountAny(parent, vnode.children[0], before, options); if (vnode.type === Comment) { const n = document.createComment(String(vnode.children[0] ?? '')); parent.insertBefore(n, before); return { nodes: [n] }; } if (vnode.type === Fragment) { const nodes = []; for (const c of vnode.children) nodes.push(...__mountChild(parent, c, before, options).nodes); return { nodes }; } if (typeof vnode.type === 'function') { if (vnode.type.__litheMount) return vnode.type.__litheMount({ parent, before, props: { ...vnode.props, children: vnode.children }, children: vnode.children, options, mountAny: __mountAny, mountChild: __mountChild }); const scope = createScope(() => vnode.type({ ...vnode.props, children: vnode.children })), mounted = withOwner(scope.owner, () => __mountChild(parent, scope.value, before, options)); onCleanup(scope.dispose); return mounted; } return mountNativeElement(parent, vnode.type, vnode.props || {}, vnode.children, before, options); }
export function mount(root, view, options = {}) { if (!root) throw new Error('mount(root, view) requires a root element.'); if (options.clear !== false) root.textContent = ''; const scope = createScope(() => { if (options.delegateEvents !== false) { const d = installDelegatedEvents(root); onCleanup(d); } return __mountChild(root, typeof view === 'function' && !view.__litheDynamic ? h(view, {}) : view, null, options); }); return () => { scope.dispose(); if (options.clearOnDispose !== false) root.textContent = ''; }; }
export function dynamic(fn) { fn.__litheDynamic = true; return fn; }
export function configureTrustedTypes(name = 'lithe', rules = {}) { if (typeof trustedTypes === 'undefined') return null; trustedTypesPolicy ||= trustedTypes.createPolicy(name, { createHTML: rules.createHTML || ((v) => v), createScriptURL: rules.createScriptURL || ((v) => v) }); return trustedTypesPolicy; }
export function trustedHTML(value) { const raw = String(value), safe = trustedTypesPolicy?.createHTML ? trustedTypesPolicy.createHTML(raw) : raw; return Object.freeze({ __trustedHTML: true, value: safe }); }
export function staticTemplate(html) { return Object.freeze({ __litheStaticTemplate: true, html: String(html) }); }
export function compiledTemplate(html, bindings = []) { return Object.freeze({ __litheCompiledTemplate: true, html: String(html), bindings }); }
export function compiledElement(type, props = null, children = []) { return Object.freeze({ __litheCompiledElement: true, type, props: props || {}, children: Array.isArray(children) ? children : [children] }); }
export function createElement(type, props, ...children) { return h(type, props, ...children); }
