function trace(type,attributes={},id=globalThis.__LITHE_CORRELATION_ID__||null){try{globalThis.__LITHE_CORRELATION_EVENT__?.(type,attributes,id);}catch{}}
function makeSource(fn,shared=false){return `${shared?'self.onconnect=(event)=>{const port=event.ports[0];port.onmessage=':'self.onmessage='}async (event)=>{const target=${shared?'port':'self'};const task=(${fn.toString()});const {id,args}=event.data;try{const value=await task(...args);target.postMessage({id,ok:true,value});}catch(error){target.postMessage({id,ok:false,error:{name:error.name,message:error.message,stack:error.stack}});}}${shared?';port.start?.();}':''}`;}
function revive(error){const e=new Error(error.message);Object.assign(e,error);return e;}
export function worker(fn,options={}){
  if(typeof fn!=='function')throw new TypeError('worker() requires a pure function.');let instance=null,url=null,seq=0;const pending=new Map();
  const ensure=()=>{if(instance)return instance;if(typeof Worker==='undefined')return null;url=URL.createObjectURL(new Blob([makeSource(fn,false)],{type:'text/javascript'}));instance=new Worker(url,{name:options.name||fn.name||'lithe-worker',type:options.type||'classic'});instance.onmessage=e=>{const job=pending.get(e.data.id);if(!job)return;pending.delete(e.data.id);e.data.ok?job.resolve(e.data.value):job.reject(revive(e.data.error));};return instance;};
  const invoke=(args,transfer)=>{const w=ensure(),traceId=globalThis.__LITHE_CORRELATION_ID__||null;trace('worker:start',{name:options.name||fn.name||'worker'});if(!w)return Promise.resolve(fn(...args)).then(value=>{trace('worker:end',{name:options.name||fn.name||'worker'});return value;},error=>{trace('worker:error',{message:error.message});throw error;});const id=++seq;return new Promise((resolve,reject)=>{pending.set(id,{resolve(value){trace('worker:end',{name:options.name||fn.name||'worker'},traceId);resolve(value);},reject(error){trace('worker:error',{message:error.message},traceId);reject(error);}});const list=transfer||options.transfer?.(args)||[];w.postMessage({id,args,traceId},list);});};
  const call=(...args)=>invoke(args);call.withTransfer=(args,transfer=[])=>invoke(args,transfer);call.terminate=()=>{instance?.terminate();instance=null;if(url)URL.revokeObjectURL(url);url=null;for(const job of pending.values())job.reject(new Error('Worker terminated'));pending.clear();};return call;
}
export function sharedWorker(fn,options={}){
  if(typeof SharedWorker==='undefined')return worker(fn,options);let instance=null,url=null,seq=0;const pending=new Map();
  const ensure=()=>{if(instance)return instance;url=URL.createObjectURL(new Blob([makeSource(fn,true)],{type:'text/javascript'}));instance=new SharedWorker(url,{name:options.name||fn.name||'lithe-shared-worker',type:options.type||'classic'});instance.port.onmessage=e=>{const job=pending.get(e.data.id);if(!job)return;pending.delete(e.data.id);e.data.ok?job.resolve(e.data.value):job.reject(revive(e.data.error));};instance.port.start?.();return instance;};
  const call=(...args)=>{const w=ensure(),id=++seq,traceId=globalThis.__LITHE_CORRELATION_ID__||null;trace('shared-worker:start',{name:options.name||fn.name||'shared-worker'},traceId);return new Promise((resolve,reject)=>{pending.set(id,{resolve(value){trace('shared-worker:end',{name:options.name||fn.name||'shared-worker'},traceId);resolve(value);},reject(error){trace('shared-worker:error',{message:error.message},traceId);reject(error);}});w.port.postMessage({id,args,traceId},options.transfer?.(args)||[]);});};call.terminate=()=>{instance?.port.close();instance=null;if(url)URL.revokeObjectURL(url);url=null;for(const job of pending.values())job.reject(new Error('SharedWorker closed'));pending.clear();};return call;
}
