import { signal, computed, state } from '../core/reactive.ts';
import { h } from '../dom/vnode.ts';

export function createDataGrid(options){
  const sort=signal(null),direction=signal('asc'),filter=signal(''),selected=signal(new Set()),active=signal({row:0,col:0}),editing=signal(null);
  const source=()=>typeof options.data==='function'?options.data():options.data||[];
  const rows=computed(()=>{let data=[...source()];if(filter.value){const q=filter.value.toLowerCase();data=data.filter(row=>Object.values(row).some(v=>String(v??'').toLowerCase().includes(q)));}if(sort.value)data.sort((a,b)=>{const av=a[sort.value],bv=b[sort.value],r=av===bv?0:av>bv?1:-1;return direction.value==='asc'?r:-r;});return data;});
  const keyOf=(row,index)=>row?.[options.rowKey||'id']??index;
  return{sort,direction,filter,rows,selected,active,editing,toggleSort(key){if(sort.value===key)direction.value=direction.value==='asc'?'desc':'asc';else{sort.value=key;direction.value='asc';}},select(row,index,multi=false){const key=keyOf(row,index);const next=new Set(multi?selected.value:[]);next.has(key)?next.delete(key):next.add(key);selected.value=next;},selectAll(){selected.value=new Set(rows.value.map((r,i)=>keyOf(r,i)));},clearSelection(){selected.value=new Set();},startEdit(rowIndex,columnKey){editing.value={rowIndex,columnKey};},commitEdit(value){const e=editing.value;if(!e)return;const row=rows.value[e.rowIndex];options.onEdit?.({row,rowIndex:e.rowIndex,columnKey:e.columnKey,value});if(options.mutable!==false&&row)row[e.columnKey]=value;editing.value=null;},cancelEdit(){editing.value=null;},moveActive(dr,dc){const cols=options.columns?.length||1;active.value={row:Math.max(0,Math.min(rows.value.length-1,active.value.row+dr)),col:Math.max(0,Math.min(cols-1,active.value.col+dc))};}};
}
export function DataGrid(props){
  const grid=createDataGrid({data:props.data,rowKey:props.rowKey,columns:props.columns,onEdit:props.onEdit,mutable:props.mutable});
  const keydown=e=>{if(e.key==='ArrowDown'){grid.moveActive(1,0);e.preventDefault();}else if(e.key==='ArrowUp'){grid.moveActive(-1,0);e.preventDefault();}else if(e.key==='ArrowRight'){grid.moveActive(0,1);e.preventDefault();}else if(e.key==='ArrowLeft'){grid.moveActive(0,-1);e.preventDefault();}else if(e.key==='Escape')grid.cancelEdit();};
  return h('div',{class:props.class,onKeydown:keydown},props.search!==false?h('input',{placeholder:'Search',onInput:e=>grid.filter.value=e.target.value}):null,h('table',{role:'grid'},h('thead',{style:props.stickyHeader?{position:'sticky',top:0,zIndex:1}:null},h('tr',null,...props.columns.map(c=>h('th',{scope:'col','aria-sort':()=>grid.sort.value===c.key?(grid.direction.value==='asc'?'ascending':'descending'):'none',onClick:()=>c.sortable!==false&&grid.toggleSort(c.key)},c.label||c.key)))),h('tbody',null,()=>grid.rows.value.map((row,ri)=>h('tr',{key:row[props.rowKey||'id'],role:'row','aria-selected':()=>grid.selected.value.has(row[props.rowKey||'id']??ri),onClick:e=>props.selectable!==false&&grid.select(row,ri,e.metaKey||e.ctrlKey)},...props.columns.map((c,ci)=>{const edit=grid.editing.value;const active=grid.active.value.row===ri&&grid.active.value.col===ci;if(edit?.rowIndex===ri&&edit.columnKey===c.key)return h('td',{role:'gridcell'},h('input',{autofocus:true,value:row[c.key]??'',onBlur:e=>grid.commitEdit(e.target.value),onKeydown:e=>{if(e.key==='Enter')grid.commitEdit(e.target.value);}}));return h('td',{role:'gridcell',tabIndex:active?0:-1,onDblclick:()=>c.editable!==false&&grid.startEdit(ri,c.key)},c.render?c.render(row[c.key],row):row[c.key]);}))))));
}
