// Lightweight dependency-free semantic checker for the TypeScript subset most application
// code uses at framework boundaries. Node's native transformer remains the syntax authority;
// this pass adds assignability checks for declarations, objects, arrays, unions and calls.
function splitTop(text,delimiter=','){const out=[];let start=0,round=0,square=0,curly=0,angle=0,quote=null;for(let i=0;i<text.length;i++){const c=text[i];if(quote){if(c==='\\')i++;else if(c===quote)quote=null;continue;}if(c==='"'||c==="'"||c==='`'){quote=c;continue;}if(c==='(')round++;else if(c===')')round--;else if(c==='[')square++;else if(c===']')square--;else if(c==='{')curly++;else if(c==='}')curly--;else if(c==='<')angle++;else if(c==='>')angle=Math.max(0,angle-1);else if(c===delimiter&&round===0&&square===0&&curly===0&&angle===0){out.push(text.slice(start,i).trim());start=i+1;}}out.push(text.slice(start).trim());return out.filter(Boolean);}
function balanced(source,start,open='{',close='}'){let depth=0,quote=null;for(let i=start;i<source.length;i++){const c=source[i];if(quote){if(c==='\\')i++;else if(c===quote)quote=null;continue;}if(c==='"'||c==="'"||c==='`'){quote=c;continue;}if(c===open)depth++;else if(c===close&&--depth===0)return i;}return source.length-1;}
function lineOf(source,index){return source.slice(0,index).split('\n').length;}
const primitive=new Set(['string','number','boolean','bigint','symbol','null','undefined','void','unknown','any','never','object']);
function named(name){return{kind:'named',name};}
function union(types){const flat=[];for(const t of types){if(t.kind==='union')flat.push(...t.types);else flat.push(t);}const seen=new Map();for(const t of flat)seen.set(typeText(t),t);return seen.size===1?[...seen.values()][0]:{kind:'union',types:[...seen.values()]};}
function typeText(t){if(!t)return'unknown';if(t.kind==='primitive')return t.name;if(t.kind==='literal')return JSON.stringify(t.value);if(t.kind==='array')return`${typeText(t.element)}[]`;if(t.kind==='union')return t.types.map(typeText).join(' | ');if(t.kind==='object')return`{ ${Object.entries(t.props).map(([k,v])=>`${k}${v.optional?'?':''}: ${typeText(v.type)}`).join('; ')} }`;if(t.kind==='generic')return`${t.name}<${t.args.map(typeText).join(', ')}>`;if(t.kind==='function')return`(${t.params.map(typeText).join(', ')}) => ${typeText(t.returns)}`;return t.name||'unknown';}
function stripOuter(text){text=text.trim();while(text[0]==='('&&text.at(-1)===')'&&balanced(text,0,'(',')')===text.length-1)text=text.slice(1,-1).trim();return text;}
export function parseType(text,env=new Map()){text=stripOuter(String(text||'').replace(/^readonly\s+/,''));if(!text)return{kind:'primitive',name:'unknown'};const unions=splitTop(text,'|');if(unions.length>1)return union(unions.map(x=>parseType(x,env)));if(text.endsWith('[]'))return{kind:'array',element:parseType(text.slice(0,-2),env)};let m=text.match(/^([A-Za-z_$][\w$]*)\s*<([\s\S]+)>$/);if(m)return{kind:'generic',name:m[1],args:splitTop(m[2]).map(x=>parseType(x,env))};if(text.startsWith('{')&&text.endsWith('}')){const props={};for(const part of splitTop(text.slice(1,-1),';').flatMap(x=>splitTop(x))){const p=part.match(/^(?:readonly\s+)?([A-Za-z_$][\w$]*|["'][^"']+["'])\s*(\?)?\s*:\s*([\s\S]+)$/);if(p){const key=p[1].replace(/^["']|["']$/g,'');props[key]={optional:Boolean(p[2]),type:parseType(p[3],env)};}}return{kind:'object',props};}if(/^['"].*['"]$/.test(text))return{kind:'literal',value:text.slice(1,-1)};if(/^-?\d+(?:\.\d+)?$/.test(text))return{kind:'literal',value:Number(text)};if(text==='true'||text==='false')return{kind:'literal',value:text==='true'};if(primitive.has(text))return{kind:'primitive',name:text};if(env.has(text))return env.get(text);return named(text);}
function literalPrimitive(v){if(v===null)return'null';return typeof v;}
function substitute(t,map){if(!t)return t;if(t.kind==='named'&&map.has(t.name))return map.get(t.name);if(t.kind==='array')return{...t,element:substitute(t.element,map)};if(t.kind==='union')return{...t,types:t.types.map(x=>substitute(x,map))};if(t.kind==='generic')return{...t,args:t.args.map(x=>substitute(x,map))};if(t.kind==='object')return{...t,props:Object.fromEntries(Object.entries(t.props).map(([k,v])=>[k,{...v,type:substitute(v.type,map)}]))};if(t.kind==='function')return{...t,params:t.params.map(x=>substitute(x,map)),returns:substitute(t.returns,map)};return t;}
function resolve(t,env,seen=new Set()){if(!t)return t;if(t.kind==='generic'){const def=env.get(t.name);if(def?.kind==='genericDef'&&!seen.has(t.name)){seen.add(t.name);const map=new Map(def.params.map((p,i)=>[p,t.args[i]||{kind:'primitive',name:'unknown'}]));return resolve(substitute(def.body,map),env,seen);}return t;}if(t.kind!=='named'||seen.has(t.name))return t;seen.add(t.name);return env.get(t.name)?resolve(env.get(t.name),env,seen):t;}
export function isTypeAssignable(from,to,env=new Map()){from=resolve(from,env);to=resolve(to,env);if(!to||to.kind==='primitive'&&['any','unknown'].includes(to.name))return true;if(from?.kind==='primitive'&&from.name==='never')return true;if(!from)return false;if(to.kind==='union')return to.types.some(t=>isTypeAssignable(from,t,env));if(from.kind==='union')return from.types.every(t=>isTypeAssignable(t,to,env));if(from.kind==='literal'){if(to.kind==='literal')return Object.is(from.value,to.value);if(to.kind==='primitive')return literalPrimitive(from.value)===to.name||(from.value===null&&to.name==='object');}
  if(from.kind==='primitive'&&to.kind==='primitive')return from.name===to.name||(from.name==='undefined'&&to.name==='void');
  if(from.kind==='array'&&to.kind==='array')return isTypeAssignable(from.element,to.element,env);
  if(from.kind==='array'&&to.kind==='generic'&&['Array','ReadonlyArray'].includes(to.name))return isTypeAssignable(from.element,to.args[0],env);
  if(from.kind==='generic'&&to.kind==='generic'&&from.name===to.name&&from.args.length===to.args.length)return from.args.every((x,i)=>isTypeAssignable(x,to.args[i],env));
  if(from.kind==='object'&&to.kind==='object'){for(const[k,p]of Object.entries(to.props)){const got=from.props[k];if(!got){if(!p.optional)return false;continue;}if(!isTypeAssignable(got.type,p.type,env))return false;}return true;}
  if(from.kind==='function'&&to.kind==='function')return from.params.length>=to.params.length&&to.params.every((p,i)=>isTypeAssignable(p,from.params[i],env))&&isTypeAssignable(from.returns,to.returns,env);
  if(from.kind==='named'&&to.kind==='named')return from.name===to.name;
  return false;}
function inferObject(text,vars,env,functions){const inner=text.slice(1,-1),props={};for(const part of splitTop(inner)){const colon=part.indexOf(':');if(colon<0){const key=part.trim();if(/^[A-Za-z_$][\w$]*$/.test(key))props[key]={optional:false,type:vars.get(key)||{kind:'primitive',name:'unknown'}};continue;}const key=part.slice(0,colon).trim().replace(/^["']|["']$/g,''),expr=part.slice(colon+1);props[key]={optional:false,type:inferExpression(expr,vars,env,functions)};}return{kind:'object',props};}
export function inferExpression(text,vars=new Map(),env=new Map(),functions=new Map()){let expr=stripOuter(String(text||'').trim().replace(/;$/,''));expr=expr.replace(/\s+as\s+const\s*$/,'');const assertion=expr.match(/^([\s\S]+?)\s+as\s+([A-Za-z_$][\w$]*(?:\[\])?)$/);if(assertion)return parseType(assertion[2],env);if(/^['"][\s\S]*['"]$/.test(expr))return{kind:'literal',value:expr.slice(1,-1)};if(/^`[\s\S]*`$/.test(expr))return{kind:'primitive',name:'string'};if(/^-?\d+(?:\.\d+)?(?:e[+-]?\d+)?$/i.test(expr))return{kind:'literal',value:Number(expr)};if(expr==='true'||expr==='false')return{kind:'literal',value:expr==='true'};if(expr==='null')return{kind:'literal',value:null};if(expr==='undefined'||expr==='void 0')return{kind:'primitive',name:'undefined'};if(expr.startsWith('[')&&expr.endsWith(']')){const parts=splitTop(expr.slice(1,-1));return{kind:'array',element:parts.length?union(parts.map(x=>inferExpression(x,vars,env,functions))):{kind:'primitive',name:'never'}};}if(expr.startsWith('{')&&expr.endsWith('}'))return inferObject(expr,vars,env,functions);if(/^new\s+Date\b/.test(expr))return named('Date');if(/^(?:async\s*)?(?:function\b|\([^)]*\)\s*=>|[A-Za-z_$][\w$]*\s*=>)/.test(expr))return{kind:'function',params:[],returns:{kind:'primitive',name:'unknown'}};const call=expr.match(/^([A-Za-z_$][\w$]*)\s*\(/);if(call&&functions.has(call[1]))return functions.get(call[1]).returns;if(/^[A-Za-z_$][\w$]*$/.test(expr))return vars.get(expr)||env.get(expr)||{kind:'primitive',name:'unknown'};if(/[+]/.test(expr)&&/['"`]/.test(expr))return{kind:'primitive',name:'string'};if(/^[\d\s+*/%().-]+$/.test(expr))return{kind:'primitive',name:'number'};return{kind:'primitive',name:'unknown'};}
function collectTypes(source,env){for(const m of source.matchAll(/\binterface\s+([A-Za-z_$][\w$]*)(?:\s*<([^>{}]+)>)?(?:\s+extends\s+([^\{]+))?\s*\{/g)){const open=source.indexOf('{',m.index),close=balanced(source,open),own=parseType(source.slice(open,close+1),env);if(m[3]){const bases=splitTop(m[3]).map(x=>resolve(parseType(x.trim(),env),env)).filter(x=>x?.kind==='object');for(const b of bases)own.props={...b.props,...own.props};}const params=m[2]?splitTop(m[2]).map(x=>x.trim().split(/\s+extends\s+/)[0].trim()):[];env.set(m[1],params.length?{kind:'genericDef',params,body:own}:own);}for(const m of source.matchAll(/\btype\s+([A-Za-z_$][\w$]*)(?:\s*<([^;=]+)>)?\s*=\s*/g)){let i=m.index+m[0].length,round=0,square=0,curly=0,angle=0,quote=null,end=i;for(;end<source.length;end++){const c=source[end];if(quote){if(c==='\\')end++;else if(c===quote)quote=null;continue;}if(c==='"'||c==="'"||c==='`'){quote=c;continue;}if(c==='(')round++;else if(c===')')round--;else if(c==='[')square++;else if(c===']')square--;else if(c==='{')curly++;else if(c==='}')curly--;else if(c==='<')angle++;else if(c==='>')angle=Math.max(0,angle-1);else if(c===';'&&round===0&&square===0&&curly===0&&angle===0)break;}const body=parseType(source.slice(i,end),env),params=m[2]?splitTop(m[2]).map(x=>x.trim().split(/\s+extends\s+/)[0].trim()):[];env.set(m[1],params.length?{kind:'genericDef',params,body}:body);}return env;}
export function collectTypeEnvironment(sources){const env=new Map();for(const source of sources)collectTypes(source,env);return env;}
function issue(source,index,code,message,file){return{severity:'error',code,file,line:lineOf(source,index),column:index-(source.lastIndexOf('\n',index-1)+1),message};}
export function semanticTypecheck(source,options={}){const file=options.filename||'<module>',env=options.env||collectTypeEnvironment([source]),vars=new Map(),functions=new Map(),issues=[];
  // Functions first so call sites can be checked regardless of declaration order.
  for(const m of source.matchAll(/\b(?:export\s+)?(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*(?:<[^>{}()]*>)?\s*\(([^)]*)\)\s*(?::\s*([^\{=>\n]+))?\s*\{/g)){const params=[];for(const p of splitTop(m[2])){const pm=p.match(/^(?:\.\.\.)?([A-Za-z_$][\w$]*)\??\s*(?::\s*([^=]+))?/);if(pm)params.push({name:pm[1],type:parseType(pm[2]||'unknown',env)});}functions.set(m[1],{params:params.map(x=>x.type),paramInfo:params,returns:parseType((m[3]||'unknown').replace(/^Promise\s*<([\s\S]+)>$/,'$1'),env)});}
  for(const m of source.matchAll(/\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*:\s*([^=;\n]+)\s*=\s*([^;\n]+)/g)){const expected=parseType(m[2],env),actual=inferExpression(m[3],vars,env,functions);vars.set(m[1],expected);if(actual.kind!=='primitive'||actual.name!=='unknown')if(!isTypeAssignable(actual,expected,env))issues.push(issue(source,m.index,'TS_ASSIGN',`Type ${typeText(actual)} is not assignable to ${typeText(expected)} for ${m[1]}.`,file));}
  for(const m of source.matchAll(/\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*([^;\n]+)/g))if(!vars.has(m[1]))vars.set(m[1],inferExpression(m[2],vars,env,functions));
  for(const [name,fn] of functions){const re=new RegExp(`\\b${name}\\s*\\(([^)]*)\\)`,'g');for(const m of source.matchAll(re)){const prefix=source.slice(Math.max(0,m.index-12),m.index);if(/function\s*$/.test(prefix))continue;const args=splitTop(m[1]);for(let i=0;i<Math.min(args.length,fn.params.length);i++){const actual=inferExpression(args[i],vars,env,functions),expected=fn.params[i];if(actual.kind==='primitive'&&actual.name==='unknown')continue;if(!isTypeAssignable(actual,expected,env))issues.push(issue(source,m.index,'TS_ARGUMENT',`Argument ${i+1} of ${name} has type ${typeText(actual)}; expected ${typeText(expected)}.`,file));}}
  }
  for(const m of source.matchAll(/\b([A-Za-z_$][\w$]*)\s*=\s*([^;\n]+)/g)){if(!vars.has(m[1])||/\b(?:const|let|var)\s+$/.test(source.slice(Math.max(0,m.index-12),m.index)))continue;const actual=inferExpression(m[2],vars,env,functions),expected=vars.get(m[1]);if(actual.kind==='primitive'&&actual.name==='unknown')continue;if(!isTypeAssignable(actual,expected,env))issues.push(issue(source,m.index,'TS_REASSIGN',`Cannot assign ${typeText(actual)} to ${m[1]} (${typeText(expected)}).`,file));}
  return{ok:issues.length===0,issues,environment:env,variables:vars,functions};}
export { typeText as formatType };
