import { state, signal, batch } from '../core/reactive.ts';
import type { Schema, ValidationIssue } from './schema.ts';

export type FieldPath = string | Array<string|number>;
export interface FieldValidationContext<T extends object>{values:T;path:Array<string|number>;signal:AbortSignal}
export type FieldValidator<T extends object>=(value:unknown,context:FieldValidationContext<T>)=>string|boolean|void|Promise<string|boolean|void>;
export interface FormOptions<T extends object>{
  initial?:T; schema?:Schema<T>; action?:(values:T)=>unknown|Promise<unknown>; onSubmit?:(values:T)=>unknown|Promise<unknown>; onChange?:(event:{path:string;value:unknown;values:T})=>void;
  fieldValidators?:Record<string,FieldValidator<T>>; asyncValidateField?:FieldValidator<T>; validateOnBlur?:boolean; name?:string;
}
export interface FormField<T extends object>{name:string;value:unknown;readonly error?:string;readonly touched:boolean;readonly dirty:boolean;touch():void;validate():Promise<boolean>;props:Record<string,unknown>}
export interface FormApi<T extends object>{values:T;errors:Record<string,string>;touched:Record<string,boolean>;dirty:Record<string,boolean>;field(name:FieldPath):FormField<T>;get(path:FieldPath):unknown;set(path:FieldPath,value:unknown,flags?:{touch?:boolean;validate?:boolean}):unknown;validate():any;validateField(path:FieldPath):Promise<boolean>;submit(event?:{preventDefault?:()=>void}):Promise<any>;reset(next?:T):unknown;readonly submitting:boolean;readonly validating:boolean;readonly submitted:boolean;readonly submitError:unknown;readonly valid:boolean;props:{onSubmit:(event?:any)=>Promise<any>;noValidate:true}}
function traceForm(type:string,attributes:Record<string,unknown>={}){try{globalThis.__LITHE_CORRELATION_EVENT__?.(type,attributes,globalThis.__LITHE_CORRELATION_ID__||null);}catch{}}
export function splitPath(path:FieldPath):Array<string|number>{if(Array.isArray(path))return path;return String(path).replace(/\[(\d+)\]/g,'.$1').split('.').filter(Boolean).map(x=>/^\d+$/.test(x)?Number(x):x);}
export function getPath(object:any,path:FieldPath):unknown{let cur=object;for(const key of splitPath(path)){if(cur==null)return undefined;cur=cur[key];}return cur;}
export function setPath(object:any,path:FieldPath,value:unknown):unknown{const parts=splitPath(path);if(!parts.length)return value;let cur=object;for(let i=0;i<parts.length-1;i++){const key=parts[i],next=parts[i+1];if(cur[key]==null||typeof cur[key]!=='object')cur[key]=typeof next==='number'?[]:{};cur=cur[key];}cur[parts.at(-1)]=value;return value;}
export function deletePath(object:any,path:FieldPath):boolean{const parts=splitPath(path);let cur=object;for(let i=0;i<parts.length-1;i++){cur=cur?.[parts[i]];if(cur==null)return false;}return delete cur[parts.at(-1)];}
const pathKey=p=>splitPath(p).join('.'),clone=v=>typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v)),equal=(a,b)=>{if(Object.is(a,b))return true;try{return JSON.stringify(a)===JSON.stringify(b);}catch{return false;}};
export function createForm<T extends Record<string,any>=Record<string,any>>(options:FormOptions<T>={} as FormOptions<T>):FormApi<T>{
  const initial=clone((options.initial||{}) as T),values=state(clone(initial)) as T,errors=state<Record<string,string>>({}),touched=state<Record<string,boolean>>({}),dirty=state<Record<string,boolean>>({}),submitting=signal(false),submitted=signal(false),submitError=signal<unknown>(null),validating=signal(false),controllers=new Map<string,AbortController>();
  const clearErrors=()=>{for(const k of Object.keys(errors))delete errors[k];};
  const validate=()=>{clearErrors();if(!options.schema)return{success:true,data:values};const r=options.schema.safeParse(values);if(!r.success)for(const issue of r.issues)errors[pathKey(issue.path)]=issue.message;return r;};
  const validateField=async name=>{const key=pathKey(name),validator=options.fieldValidators?.[key]||options.asyncValidateField;if(!validator){validate();return!errors[key];}controllers.get(key)?.abort();const controller=new AbortController();controllers.set(key,controller);validating.value=true;try{const r=await validator(getPath(values,key),{values,path:splitPath(key),signal:controller.signal});if(controller.signal.aborted)return false;if(typeof r==='string')errors[key]=r;else if(r===false)errors[key]='Invalid value';else delete errors[key];return!errors[key];}catch(e){if(e?.name==='AbortError')return false;errors[key]=e.message||'Validation failed';return false;}finally{if(controllers.get(key)===controller)controllers.delete(key);validating.value=controllers.size>0;}};
  const setValue=(name,value,flags={})=>{const key=pathKey(name);setPath(values,key,value);dirty[key]=!equal(getPath(values,key),getPath(initial,key));if(flags.touch)touched[key]=true;options.onChange?.({path:key,value,values});if(flags.validate)validateField(key);return value;};
  const field=name=>{const key=pathKey(name);return{name:key,get value(){return getPath(values,key);},set value(v){setValue(key,v);},get error(){return errors[key];},get touched(){return!!touched[key];},get dirty(){return!!dirty[key];},touch(){touched[key]=true;},validate(){return validateField(key);},props:{name:key,get value(){return getPath(values,key)??'';},onInput(e){setValue(key,e.target.type==='checkbox'?e.target.checked:e.target.value);},onChange(e){if(e.target.type==='checkbox')setValue(key,e.target.checked);},onBlur(){touched[key]=true;if(options.validateOnBlur!==false)validateField(key);}}};};
  const submit=async event=>{event?.preventDefault?.();submitted.value=true;submitError.value=null;traceForm('form:submit:start',{name:options.name||null});const r=validate();if(!r.success){traceForm('form:submit:invalid',{issues:Object.keys(errors).length});return{success:false,errors};}submitting.value=true;try{const data=await(options.action||options.onSubmit)?.(r.data);traceForm('form:submit:end',{name:options.name||null});return{success:true,data};}catch(e){submitError.value=e;if(e?.issues)for(const issue of e.issues)errors[pathKey(issue.path)]=issue.message;traceForm('form:submit:error',{message:e.message});return{success:false,error:e};}finally{submitting.value=false;}};
  const reset=(next=initial)=>batch(()=>{for(const k of Object.keys(values))delete values[k];Object.assign(values,clone(next));for(const o of[errors,touched,dirty])for(const k of Object.keys(o))delete o[k];submitting.value=false;submitted.value=false;submitError.value=null;});
  return{values,errors,touched,dirty,field,get:getPath.bind(null,values),set:setValue,validate,validateField,submit,reset,get submitting(){return submitting.value;},get validating(){return validating.value;},get submitted(){return submitted.value;},get submitError(){return submitError.value;},get valid(){return Object.keys(errors).length===0;},props:{onSubmit:submit,noValidate:true}} as FormApi<T>;
}
export function formDataToObject(formData:FormData):Record<string,FormDataEntryValue|FormDataEntryValue[]>{const out={};for(const[k,v]of formData.entries())out[k]=k in out?(Array.isArray(out[k])?[...out[k],v]:[out[k],v]):v;return out;}
