import path from 'node:path';
function matchBrace(code,start){let depth=0,quote=null;for(let i=start;i<code.length;i++){const c=code[i];if(quote){if(c==='\\')i++;else if(c===quote)quote=null;continue;}if(c==='"'||c==="'"||c==='`'){quote=c;continue;}if(c==='/'&&code[i+1]==='/'){i+=2;while(i<code.length&&code[i]!=='\n')i++;continue;}if(c==='/'&&code[i+1]==='*'){i+=2;while(i<code.length&&!(code[i]==='*'&&code[i+1]==='/'))i++;i++;continue;}if(c==='{')depth++;else if(c==='}'&&--depth===0)return i;}return-1;}
function statementEnd(code,start){let round=0,square=0,curly=0,quote=null;for(let i=start;i<code.length;i++){const c=code[i];if(quote){if(c==='\\')i++;else if(c===quote)quote=null;continue;}if(c==='"'||c==="'"||c==='`'){quote=c;continue;}if(c==='(')round++;else if(c===')')round--;else if(c==='[')square++;else if(c===']')square--;else if(c==='{')curly++;else if(c==='}')curly--;else if(c===';'&&!round&&!square&&!curly)return i+1;}return code.length;}
function refs(code,name,start,end){const rest=code.slice(0,start)+code.slice(end);return[...rest.matchAll(new RegExp(`\\b${name}\\b`,'g'))].length;}
function pureInitializer(expr){expr=expr.trim();return/^(?:async\s*)?(?:function\b|\([^)]*\)\s*=>|[A-Za-z_$][\w$]*\s*=>)/.test(expr)||/^(?:null|undefined|true|false|-?\d+(?:\.\d+)?n?|['"`][\s\S]*['"`]|\[[\s\S]*\]|\{[\s\S]*\})$/.test(expr)&&!/\b(?:new|await|yield|throw|delete|import)\b|\w\s*\(/.test(expr);}
export function treeShakeModule(code,usedExports=new Set(['*']),options={}){if(usedExports.has('*')||options.entry)return{code,removed:[]};const removed=[],edits=[];const used=name=>usedExports.has(name)||usedExports.has('default');
  for(const m of code.matchAll(/\bexport\s+(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/g)){const name=m[1];if(used(name))continue;const open=code.indexOf('{',m.index),close=matchBrace(code,open);if(close<0)continue;if(refs(code,name,m.index,close+1)===0){edits.push({start:m.index,end:close+1,text:''});removed.push(name);}else edits.push({start:m.index,end:m.index+7,text:''});}
  for(const m of code.matchAll(/\bexport\s+class\s+([A-Za-z_$][\w$]*)/g))if(!used(m[1]))edits.push({start:m.index,end:m.index+7,text:''});
  for(const m of code.matchAll(/\bexport\s+(const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*/g)){const name=m[2];if(used(name))continue;const end=statementEnd(code,m.index),eq=code.indexOf('=',m.index),expr=code.slice(eq+1,end).replace(/;\s*$/,'');if(refs(code,name,m.index,end)===0&&pureInitializer(expr)){edits.push({start:m.index,end,text:''});removed.push(name);}else edits.push({start:m.index,end:m.index+7,text:''});}
  for(const m of code.matchAll(/\bexport\s*\{([^}]+)\}\s*;?/g)){const keep=[];for(const part of m[1].split(',').map(x=>x.trim()).filter(Boolean)){const mm=part.match(/^([A-Za-z_$][\w$]*)(?:\s+as\s+([A-Za-z_$][\w$]*))?$/);if(!mm||used(mm[2]||mm[1]))keep.push(part);else removed.push(mm[2]||mm[1]);}edits.push({start:m.index,end:m.index+m[0].length,text:keep.length?`export { ${keep.join(', ')} };`:''});}
  let out=code;for(const e of edits.sort((a,b)=>b.start-a.start))out=out.slice(0,e.start)+e.text+out.slice(e.end);return{code:out,removed:[...new Set(removed)]};}
function resolve(from,spec){if(spec.startsWith('/'))return spec.slice(1);if(spec.startsWith('.'))return path.posix.normalize(path.posix.join(path.posix.dirname(from),spec));return spec;}
export function collectUsedExports(modules,entries=[]){const used=new Map();for(const entry of entries)used.set(entry,new Set(['*']));const add=(target,name)=>{if(!modules.has(target))return;let set=used.get(target);if(!set)used.set(target,set=new Set());set.add(name);};for(const[from,code]of modules){for(const m of code.matchAll(/import\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"]/g)){const target=resolve(from,m[2]);for(const part of m[1].split(',').map(x=>x.trim()).filter(Boolean)){const mm=part.match(/^([A-Za-z_$][\w$]*)(?:\s+as\s+[A-Za-z_$][\w$]*)?$/);if(mm)add(target,mm[1]);}}for(const m of code.matchAll(/import\s+([A-Za-z_$][\w$]*)\s+from\s*['"]([^'"]+)['"]/g))add(resolve(from,m[2]),'default');for(const m of code.matchAll(/import\s*\*\s*as\s+\w+\s+from\s*['"]([^'"]+)['"]/g))add(resolve(from,m[1]),'*');for(const m of code.matchAll(/export\s*\*\s*from\s*['"]([^'"]+)['"]/g))add(resolve(from,m[1]),'*');for(const m of code.matchAll(/import\s*\(\s*['"]([^'"]+)['"]\s*\)/g))add(resolve(from,m[1]),'*');for(const m of code.matchAll(/(?:eventSymbol|capturedEventSymbol)\(\s*['"]([^'"]+)['"]\s*,\s*['"]([^'"]+)['"]/g))add(resolve(from,m[1]),m[2]);}return used;}
