import fs from 'node:fs/promises';
import path from 'node:path';
import { exists, walk } from './shared.ts';

function routeFromFile(rel){
  let p=rel.replace(/\\/g,'/').replace(/\.(?:jsx?|tsx?)$/i,'').replace(/\/(?:index|page)$/,'').replace(/^(?:routes)\/?/,'');
  p=p.replace(/\[\.\.\.([^\]]+)\]/g,':$1*').replace(/\[([^\]]+)\]/g,':$1').replace(/\([^/]+\)\/?/g,'');
  return '/'+p.replace(/^\/+|\/+$/g,'');
}
function paramsOf(route){const out=[];for(const part of route.split('/'))if(part.startsWith(':')){const raw=part.slice(1),rest=raw.endsWith('*');out.push({name:rest?raw.slice(0,-1):raw,rest});}return out;}
function q(s){return JSON.stringify(s);}
function actionDecls(code,file){
  const result=[],seen=new Set();
  const generic=/export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*server\s*<\s*([^,>]+)\s*,\s*([^>]+)\s*>\s*\(/g;let m;
  while((m=generic.exec(code))){result.push({name:m[1],input:m[2].trim(),output:m[3].trim(),file});seen.add(m[1]);}
  const typed=/export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*server\s*\(\s*(?:async\s*)?\(\s*[A-Za-z_$][\w$]*\s*:\s*([^,)]+)[^)]*\)\s*(?::\s*(?:Promise\s*<\s*([^>]+)\s*>|([^=\n]+)))?\s*=>/g;
  while((m=typed.exec(code)))if(!seen.has(m[1])){result.push({name:m[1],input:m[2].trim(),output:(m[3]||m[4]||'unknown').trim(),file});seen.add(m[1]);}
  const plain=/export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*server\s*\(/g;while((m=plain.exec(code)))if(!seen.has(m[1]))result.push({name:m[1],input:'unknown',output:'unknown',file});
  return result;
}
export async function generateTypes(projectDir,options={}){
  const root=path.resolve(projectDir),src=path.join(root,'src'),routeDir=path.join(src,'routes');
  const routeFiles=await exists(routeDir)?(await walk(routeDir)).filter(f=>/\.(?:js|jsx|ts|tsx)$/.test(f)):[];
  const routes=routeFiles.map(f=>routeFromFile(path.relative(src,f))).filter((x,i,a)=>a.indexOf(x)===i).sort();
  const all=await exists(src)?(await walk(src)).filter(f=>/\.(?:js|jsx|ts|tsx)$/.test(f)):[];const actions=[];
  for(const file of all){const code=await fs.readFile(file,'utf8');actions.push(...actionDecls(code,path.relative(root,file).replace(/\\/g,'/')));}
  const lines=['// Generated by Lithe. Do not edit.','export interface LitheRouteParams {'];
  for(const route of routes){const ps=paramsOf(route);lines.push(`  ${q(route)}: ${ps.length?`{ ${ps.map(p=>`${q(p.name)}: string${p.rest?'[]':''}`).join('; ')} }`:'Record<string, never>'};`);}lines.push('}','export type LitheRoutePath = keyof LitheRouteParams;','export interface LitheServerActions {');
  for(const a of actions)lines.push(`  ${q(a.name)}: (input: ${a.input}) => Promise<${a.output}>; // ${a.file}`);lines.push('}');
  const out=path.resolve(root,options.out||'lithe.generated.d.ts');await fs.writeFile(out,lines.join('\n')+'\n');return{out,routes,actions};
}
